### ISSUE TITLE
post() global function - htmlentities options

### ISSUE THREAD

**Issue by dremecker** [bulton-fr/bfw#69]
Dans la fonction secure(), appelée par la fonction globale post(), htmlentities est forcé sur le charset UTF-8. La valeur par défaut est "ini_get("default_charset")" ce qui permet d'utiliser le charset définit dans le php.ini soit par le développeur, soit par l'hébergeur.

Il n'est pas question de remettre en cause ici l’intérêt d'utiliser l'unicode en lieu et place de l'ISO, mais de permettre à n'importe qui de pouvoir utiliser BFW quelque soit son charset.
# improvement

**Comment by bulton-fr** [comment]
Un fix vient d'être commité afin d'utiliser la valeur de l'ini.
Malgré tout, souhaitant gardé le forçage à l'unicode, je définie via ini_set à unicode dans le chargement du framework. Avec possibilité de désactivé ce forçage.

Je laisse le ticket ouvert. Je dois reporter la modification sur la v3 en cours de dev.

**Comment by bulton-fr** [comment]
Fixed into the 3.0 version too.
