### ISSUE TITLE
[3.0] BFW_PATH vs ROOT_PATH

### ISSUE THREAD

**Issue by dremecker** [bulton-fr/bfw#73]
Lors du processus d'installation, la constante BFW_PATH est utilisée en lieu et place de la constante ROOT_PATH comme indiqué dans [Migration v2.2 vers v3.0](https://github.com/bulton-fr/bfw/wiki/Migration-v2.2-vers-v3.0#constantes).

Il faudrait au choix : 
- renommer BFW_PATH en ROOT_PATH.
- OU inclure cette précision dans la documentation qui sera consacrée à la création de modules.

**Comment by bulton-fr** [comment]
En tenant compte du #77, une modification de fond est à faire pour faire fonctionner la class Application (ou une class étendue) autour du module. Dans ce cadre il sera théoriquement possible de définir les constantes du framework via la class Application.
