### ISSUE TITLE
[3.0] bfw_installModules options + arguments

### ISSUE THREAD

**Issue by dremecker** [bulton-fr/bfw#75]
Lorsque l'on souhaite passer des arguments aux options du script bfw_installModules, nous sommes obligés de le faire par "affectation de valeur" comme pour une variable classique.

Cela n'est pas un problème en soit quand on sait ou chercher l'information, néanmoins, ce comportement n'est pas classique d'un point de vue "script bash" / cli.

Exemple 
`bfw_installModules --reinstall=true --module=module_name`

en lieu et place de 
`bfw_installModules --reinstall --module module_name`

S'il n'est pas possible de faire autrement, ou si cela est voulu pour diverses raisons, serait-il possible au moins de mettre à jour l'aide pour tenir compte de cette particularité ?

**Comment by bulton-fr** [comment]
Il s'agit d'une limitation de la fonction [getopt](http://php.net/manual/fr/function.getopt.php) de php.

> Note: Les valeurs optionnelles n'acceptent pas l'espace comme séparateur.

J'ai donc mis à jour le help de la commande.
