### ISSUE TITLE
[3.0] \BFW\Form checkToken() + Exception

### ISSUE THREAD

**Issue by dremecker** [bulton-fr/bfw#76]
La méthode checkToken() lève des exceptions si le token n'est pas trouvé dans les données de la session au lieu de retourner un false.

Cela pose problème dans le cas ou le token est créé puis vérifié depuis la même page. Ce type d'application lève une exception incompréhensible par le visiteur lambda alors que les session-timeout sont monnaie courante.

Je propose de laisser l'intégrateur gérer lui même ce retour négatif sans lever d'exception. 

Il est également possible de créer un attribut de type "checkStatus" accessible en lecture pour permettre à l'utilisateur de savoir exactement d’où le problème vient en cas de retour à false.

**Comment by bulton-fr** [comment]
La méthode `hasToken` a été ajoutée afin de vérifier s'il y a un token avant d'appeler `getToken` ou `checkToken`.

`getToken` ne peux remplir son rôle de récupérer un token s'il n'y en a pas. Tout comme `checkToken` ne peux pas non plus remplir son rôle de vérifier si le token correspond s'il n'y en a pas. Ainsi, je considère comme normal qu'elles lèvent une exception si aucun token n'existe du fait qu'elle ne puissent pas remplir leurs rôle dans ce genre de cas.
