### ISSUE TITLE
 [3.0] \BFW\Helpers\Secure htmlentities() before SQL Secure Method

### ISSUE THREAD

**Issue by aetiom** [bulton-fr/bfw#85]
HTML processing (with htmlentities) should be done before SQL securing (quoting or slashing).

https://github.com/bulton-fr/bfw/blob/050cef3a54a1bb89affa42a58b26b993da3a0145/src/Helpers/Secure.php#L91

**Comment by bulton-fr** [comment]
Sql securing is not doing anymore into this helper since your pull-request #87 has been merged. So I close.
