### ISSUE TITLE
[3.0] htmlentities parameters

### ISSUE THREAD

**Issue by aetiom** [bulton-fr/bfw#86]
For security reasons we need to encode in html every possible things, so ENT_QUOTES should be prefered to ENT_COMPAT.

If it's not possible, other option would be to let user call himself htmlentities() or to let him push a callback function into secureData static method for html processing.

$data = htmlentities($data, ENT_QUOTES | ENT_HTML401);

https://github.com/bulton-fr/bfw/blob/050cef3a54a1bb89affa42a58b26b993da3a0145/src/Helpers/Secure.php#L92

**Comment by bulton-fr** [comment]
`ENT_QUOTES` is used since your pull-request #87 has been merged. So I close.
